export { InMemoryRepository } from './memory-repository.js';
export {
  announcementAudience,
  plannedWork,
  type Announcement,
  type AuditEntry,
  type BindAttempt,
  type Building,
  type TariffKind,
  type TariffRecord,
  type Equipment,
  type StoredFile,
  type HandoffFilter,
  type HouseContact,
  type HousePartner,
  type HouseService,
  type Repository,
  type RequestFilter,
  type Resident,
  type SupportFilter,
  type VisitFilter,
} from './repository.js';
export {
  DESCRIPTION_IN_NOTICE,
  actionsFor,
  createCollectingNotifier,
  describePlace,
  formatAcceptanceReminder,
  formatAssignment,
  formatAutoConfirmed,
  formatBreachForStaff,
  formatBroadcast,
  formatDeadlineWarning,
  formatGuestEntry,
  formatInspection,
  formatMessage,
  formatNeighbourAlert,
  formatNeighbourQuestion,
  formatNewRequest,
  formatOverdue,
  formatStatusChange,
  formatWorksFinished,
  formatWorksSoon,
  formatWorksStarted,
  notifyAbout,
  type NoticeAbout,
  type Notification,
  type NotificationAction,
  type Notifier,
  type OutgoingFile,
} from './notifier.js';
export {
  JOIN_LOCK_PREFIX,
  REQUESTS_PER_HOUR,
  SAME_REQUEST_WINDOW_MS,
  answerAlert,
  assessQueue,
  canKnockUpstairs,
  closeAcceptedBySilence,
  describeFromAttachments,
  escalationFor,
  sendComplaint,
  knockUpstairs,
  objectPassport,
  remindAboutAcceptance,
  remindAboutOverdue,
  remindAboutWorks,
  unheardVoice,
  warnAboutDeadlines,
  asRequest,
  sectionFor,
  submitProblem,
  surveyOf,
  type AlertAnswer,
  type AlertAnswerResult,
  type EscalationOffer,
  type KnockCommand,
  type SurveyedApartment,
  type ObjectPassport,
  type RequestWithRisk,
  type SubmitResult,
  type SubmittedRequest,
  type Transcriber,
} from './incidents.js';
export {
  MAX_OPTIONS,
  clarifyTarget,
  retargetRequest,
  type Clarification,
  type RetargetCommand,
  type TargetOption,
} from './clarify.js';
export {
  ANSWER_MAX_LENGTH,
  ASSISTANT_KNOWLEDGE,
  ASSISTANT_STARTERS,
  CAPABILITIES,
  OFF_TOPIC,
  OFF_TOPIC_STAFF,
  STAFF_KNOWLEDGE,
  askAssistant,
  capabilitiesFor,
  capabilityFor,
  findCapability,
  knowledgeFor,
  offTopicFor,
  startersFor,
  type AssistantAnswer,
  type Capability,
} from './assistant.js';
export {
  classifyIntent,
  understandRequest,
  type AssistFields,
  type AssistInput,
  type ClarifyFields,
  type ClarifyInput,
  type DoingFields,
  type DoingInput,
  type HouseContext,
  type RouteFields,
  type RouteInput,
  type Intent,
  type Place,
  type QuestionTopic,
  type ReadIntent,
  type Reasoner,
  type ReasonedFields,
  type Understanding,
} from './reasoner.js';
export { answerAboutHouse, describeHouseNow, type HouseAnswer } from './answers.js';
export { summariseReport } from './digest-text.js';
export {
  PAYMENTS_LIMIT,
  chargesForResident,
  payCharges,
  paymentHistory,
  periodOf,
  type PaymentGateway,
  type Receipt,
} from './billing.js';
export { createMockPayments, type MockPayments, type MockPaymentsOptions } from './billing-mock.js';
export {
  GUEST_CODE_MINUTES,
  SENSOR_KINDS,
  SENSOR_SILENCE_HOURS,
  VIEW_JOURNAL_MINUTES,
  activeGuestCodes,
  collapseViews,
  isSensor,
  isSilent,
  revokeGuestCode,
  sensorsFor,
  devicesAt,
  devicesFor,
  inviteGuest,
  journalFor,
  openByCode,
  openDevice,
  sendSnapshot,
  viewDevice,
  type Device,
  type DeviceDeps,
  type DeviceEvent,
  type DeviceHub,
  type DeviceKind,
  type GuestCode,
  type Snapshot,
} from './devices.js';
export {
  createMockCapitalRepair,
  type CapitalRepairDirectory,
  type CapitalRepairPlan,
  type CapitalRepairWork,
  type MockCapitalRepairOptions,
} from './capital.js';
export { createMockHub, type MockHub, type MockHubOptions } from './devices-mock.js';
export {
  OUTAGE_TITLES,
  affectedBuildings,
  createHttpCityFeed,
  createMockCityFeed,
  importOutages,
  normalizeAddress,
  outageCategory,
  parseOutage,
  sameHouse,
  type CityFeed,
  type CityOutage,
  type HttpCityFeedOptions,
  type MockCityFeedOptions,
  type OutageImport,
  type OutageResource,
} from './city.js';
export {
  createMockMeetings,
  type MeetingDecision,
  type MeetingNotice,
  type MeetingProtocol,
  type MeetingRegistry,
  type MockMeetingsOptions,
} from './meetings.js';
export { raiseSensorAlarm } from './sensors.js';
export { AHEAD_DAYS, houseAhead, houseNow, type HouseEvent, type HouseNow } from './now.js';
export { announceIncident, announceResolved } from './broadcast.js';
export { doingFor, type Doing } from './doing.js';
export { supportRequest, supportableFor, type SupportResult } from './support.js';
export {
  SUPPORT_PAGE,
  answerSupport,
  askSupport,
  closeSupport,
  describeAsker,
  describeTickets,
  formatTicket,
  listSupportFor,
  supportTicket,
  waitingSupport,
  type AnswerSupportCommand,
  type AskSupportCommand,
  type TicketCard,
} from './helpdesk.js';
export {
  DEFAULT_BOT_NAME,
  drawSticker,
  sendSticker,
  sendStickerSheet,
  stickerFor,
  stickerSheet,
  stickerStyles,
  stickersFor,
  styleOf,
  type SendStickerCommand,
  type SentSticker,
  type StickerRenderer,
  type StickerStyleView,
} from './stickers.js';
export { equipmentHealth, type EquipmentHealth } from './health.js';
export {
  readMeterPhoto,
  visionFailed,
  type MeterVision,
  type MeterVisionDeps,
  type ReadMeterPhotoCommand,
} from './meter-vision.js';
export {
  housePlan,
  type FlatState,
  type HousePlan,
  type PlanAlert,
  type PlanEntrance,
  type PlanFlat,
  type PlanRiser,
} from './plan.js';
export { assignRole, listPeople, roleTitle, setDuty, setServedBuildings, type Person } from './roles.js';
export {
  assertApartment,
  atBuilding,
  contactsFor,
  formatContacts,
  homeBuildingOf,
  homeOf,
  housed,
  listServedBuildings,
  needsApartment,
  publicHouseOf,
  servedBy,
  type HouseContacts,
  type ServedBuilding,
} from './buildings.js';
export { handOverBuilding, type HandOverCommand, type HandOverResult } from './handover.js';
export { acceptLegal, legalAccepted } from './legal.js';
export { dossierFor, queueLine } from './dossier.js';
export { assertSaid, saysSomething } from './said.js';
export { portfolio, type BuildingLine } from './portfolio.js';
export { formatMomentAt, houseZone, zoneOf } from './zone.js';
export {
  checkInspectionItem,
  listInspections,
  planInspections,
  proveInspection,
  type CheckCommand,
  type ProveCommand,
} from './inspections.js';
export {
  countForDigest,
  formatDigest,
  sendMorningDigest,
  sendMorningDigests,
  type DigestCounts,
} from './digest.js';
export {
  createSweeper,
  type SweepOptions,
  type SweepReport,
  type SweepState,
  type SweepStore,
} from './sweep.js';
export { MAX_FILE_BYTES, fileIdFromToken, isOwnFile, readFile, uploadFile } from './files.js';
export {
  BIND_ATTEMPTS,
  bindApartment,
  bindApartmentByStaff,
  listApartmentsFor,
  listUnbound,
  unbindApartment,
  type ApartmentOption,
  type BindResult,
  type UnboundResident,
} from './binding.js';
export {
  apartmentsOf,
  listOwnApartments,
  useApartment,
  withApartment,
  withoutApartment,
  type OwnApartment,
} from './apartments.js';
export {
  choiceTitle,
  closeDuePolls,
  closePoll,
  formatArea,
  POLL_REMINDER_DAYS,
  formatPollResult,
  formatProtocol,
  remindAboutPolls,
  listPollsFor,
  pollProtocol,
  startPoll,
  vote,
  type ClosedPoll,
  type PollTextOptions,
  type PollView,
  type StartPollCommand,
  type VoteCommand,
} from './voting.js';
export {
  elderOf,
  elderForEntrance,
  isElder,
  startElderPoll,
  type ElderPollCommand,
} from './elders.js';
export {
  callMeeting,
  formatDemand,
  listInitiativesFor,
  startInitiative,
  supportInitiative,
  type CallMeetingCommand,
  type InitiativeView,
  type SignCommand,
  type StartInitiativeCommand,
} from './initiatives.js';
export {
  AUDIT_ACTIONS,
  AUDIT_PAGE,
  formatAudit,
  listAudit,
  recordAction,
  type AuditAction,
} from './audit.js';
export { BOM, csvFrom, type Table } from './csv.js';
export { lastMonth, readingsCsv, readingsTable, type ExportPeriod } from './export.js';
export { sendReadingsExport, sendRequestsExport, type SentExport } from './exports-to-chat.js';
export { isMuted, listNotices, setNotice, wanting, type NoticeView } from './notices.js';
export { contactForRequest, forgetContact, saveContact } from './contact.js';
export {
  DEBT_MONTHS,
  arrearsFor,
  debtRange,
  withoutPeriod,
  formatDebt,
  formatDebtShort,
  payArrears,
  periodTitle,
  remindAboutDebt,
  type Debt,
  type DebtPeriod,
} from './debt.js';
export {
  EQUIPMENT_TEMPLATE,
  addBuilding,
  bindHouseChat,
  buildingByChat,
  importEquipment,
  makeManager,
  openBuilding,
  releaseHouseChat,
  unbindHouseChat,
  updateBuilding,
  type BuildingCard,
  type EquipmentImport,
} from './setup.js';
export { DEMO_ROLES, demoRoles, takeDemoRole, type DemoRole } from './demo.js';
export {
  MANUAL_CHANNEL,
  answerHandoff,
  formatAnswered,
  formatHandoff,
  formatPassed,
  handoffsOf,
  passRequest,
  responsibilityOf,
  waitingHandoffs,
  type AnswerHandoffInput,
  type HandoffGateway,
  type HandoffReceipt,
  type OutboundHandoff,
  type PassRequestInput,
  type ResponsibilityView,
} from './handoff.js';
export { createMockHandoffs, type MockHandoffOptions } from './handoff-mock.js';
export {
  dropVisit,
  formatVisit,
  listVisitsFor,
  markVisitDone,
  receptionFor,
  recordVisit,
  setReception,
  takeVisit,
  type BookVisitCommand,
  type Reception,
  type ReceptionHoursCommand,
  type RecordVisitCommand,
  type VisitCard,
} from './visits.js';
export {
  APARTMENTS_TEMPLATE,
  importApartments,
  parseApartments,
  type ImportProblem,
  type ImportResult,
  type ImportedApartment,
} from './import.js';
export {
  TARIFF_KINDS,
  listTariffs,
  setTariff,
  tariffTitle,
  tariffUnit,
  tariffsAt,
  tariffsFor,
  type SetTariffCommand,
  type TariffView,
} from './tariffs.js';
export {
  FORGOTTEN_NAME,
  exportPersonalData,
  forgetResident,
  formatPersonalData,
  personalDataSummary,
  type PersonalData,
  type PersonalReading,
  type PersonalRequest,
  type PersonalVote,
} from './privacy.js';
export {
  daysLeftPhrase,
  meterHistory,
  metersFor,
  pendingReadings,
  meterKindsIn,
  meterNamedIn,
  readingInWords,
  readingProgress,
  remindAboutReadings,
  submitReading,
  type MeterState,
  type ReadingInWords,
  type ReadingProgress,
  type ReadingPeriod,
  type ReadingResult,
  type SubmitReadingCommand,
} from './meters.js';
export {
  DEBTORS_SHOWN,
  formatHouseDebt,
  formatHouseDebtShort,
  type DebtorsPage,
  houseDebt,
  remindDebtor,
  type Debtor,
  type HouseDebt,
} from './collection.js';
export {
  addHouseMeter,
  commonNeedsShare,
  houseMetersFor,
  knownForCommon,
  latestCommonNeeds,
  remindAboutHouseMeters,
  submitHouseReading,
  type AddHouseMeterCommand,
  type HouseMeterState,
  type HouseReadingResult,
  type KnownForCommon,
  type SubmitHouseReadingCommand,
} from './house-meters.js';
export {
  buildingReport,
  exportRequests,
  requestsTable,
  formatReport,
  formatReportShort,
  listAssignable,
  type BuildingReport,
  type NamedQuality,
  type StaffMember,
} from './report.js';
export { QUALITY_DAYS, formatQuality, formatQualityShort, houseQuality, type HouseQuality } from './quality.js';
export {
  aimBroadcast,
  broadcastTargets,
  canAct,
  canActNow,
  commentRequest,
  createServiceRequest,
  describeContext,
  ensureResident,
  getRequestFor,
  listAnnouncementsFor,
  listRequestsFor,
  publishAnnouncement,
  sendBroadcast,
  transitionRequest,
  type AnnouncementCommand,
  type BroadcastAim,
  type BroadcastCommand,
  type BroadcastEntrance,
  type BroadcastResult,
  type BroadcastRiser,
  type BroadcastTargets,
  type CommentCommand,
  type AppDeps,
  type Lock,
  type ContextDescription,
  type CreateRequestCommand,
  CLOSED_PAGE,
  type RequestPage,
  type RequestScope,
  type TransitionCommand,
} from './use-cases.js';
