export {
  PROBLEM_OBJECT_THRESHOLD,
  assigneeQuality,
  categoryLoad,
  confirmedIncidents,
  createdIn,
  dailyLoad,
  lastDays,
  previousPeriod,
  problemObjects,
  summarize,
  summarizePeriod,
  type AssigneeQuality,
  type BuildingSummary,
  type CategoryLoad,
  type IncidentSummary,
  type Period,
  type PeriodSummary,
  type ProblemObject,
} from './analytics.js';
export {
  AFTER_VISIT_HOURS,
  MISSED_VISIT_GRACE_HOURS,
  MISSED_VISIT_LIMIT,
  dropVisitSlot,
  VISIT_WINDOW_DAYS,
  VISIT_WINDOW_HOURS,
  VISIT_WINDOW_MINUTES,
  accessRefused,
  missVisit,
  missedVisits,
  needsAccess,
  offerVisit,
  pickVisit,
  visitAhead,
  visitWindows,
  type Appointment,
} from './appointment.js';
export {
  DISPUTE_DAYS,
  canDispute,
  disputeRejection,
  rejectedAt,
  rejectionReason,
  rejectionUpheld,
  type DisputeCheck,
} from './dispute.js';
export {
  audienceForTarget,
  describeAudience,
  describeTarget,
  flatAbove,
  isInAudience,
  selectAudience,
  targetName,
} from './audience.js';
export {
  BROADCAST_FLATS_LIMIT,
  BROADCAST_KINDS,
  BROADCAST_MAX_LENGTH,
  broadcastText,
  describeScope,
  noticeForScope,
  scopeAudience,
  type BroadcastKind,
  type BroadcastScope,
} from './broadcast.js';
export {
  LEGAL_DOCUMENTS,
  LEGAL_NOTICE,
  LEGAL_UPDATED,
  LEGAL_VERSION,
  formatLegal,
  legalDocument,
  legalDocuments,
  legalUpdated,
  type LegalDocument,
} from './legal.js';
export {
  BASIS,
  PLAIN,
  basisFor,
  deadlineBasisFor,
  type BasisKey,
  type BasisKind,
} from './basis.js';
export {
  APARTMENT_CODE_ALPHABET,
  APARTMENT_CODE_LENGTH,
  APARTMENT_KEY_PREFIX,
  apartmentCodeFrom,
  apartmentKeyOf,
  apartmentKeyParam,
  isApartmentCode,
  normalizeApartmentCode,
} from './apartment-code.js';
export {
  SECTION_PREFIX,
  START_PARAM_PATTERN,
  botLinkTo,
  buildBotDeepLink,
  buildDeepLink,
  decodeTarget,
  encodeTarget,
  isSameTarget,
  isValidStartParam,
  sectionParam,
  provesPresence,
} from './deep-link.js';
export {
  MAX_TITLE_LENGTH,
  createRequest,
  MAX_DESCRIPTION_LENGTH,
  formatRequestNumber,
  isBlockage,
  normLimitFor,
  requestNumberIn,
  suggestCategory,
  suggestPriority,
  summarizeDescription,
  type CreateRequestInput,
} from './request.js';
export {
  ESCALATION_OVERRUN_FACTOR,
  MOSCOW_TIME_NOTE,
  buildComplaint,
  canEscalate,
  type ComplaintInput,
  type EscalationCheck,
} from './escalation.js';
export {
  CONFIRMED_INCIDENT_REPORTERS,
  SUPPORT_NOTICE_AT,
  JOIN_WINDOW_HOURS,
  LOCAL_EVIDENCE_ANSWERS,
  SHARED_INFRASTRUCTURE,
  audienceAsTarget,
  audienceCovers,
  audiencesOverlap,
  findJoinable,
  hasAnswered,
  hasReported,
  isConfirmedIncident,
  isSharedInfrastructure,
  joinRequest,
  leaveRequest,
  unaffected,
  markUnaffected,
  promoteToShared,
  reporterIds,
  reportersCount,
  spreadOf,
  type JoinCandidate,
  type LocatedRequest,
  type Spread,
  type SpreadView,
} from './incident.js';
export {
  NOTICE_TO_ADMIN_DAYS,
  NOTICE_TO_OWNERS_DAYS,
  PAPER_CUTOFF_HOURS,
  PROTOCOL_STORAGE_YEARS,
  PROTOCOL_TO_INSPECTION_DAYS,
  PROTOCOL_TO_MANAGEMENT_DAYS,
  PUBLISH_HOURS,
  VOTING_MAX_DAYS,
  VOTING_MIN_DAYS,
  meetingSchedule,
  type MeetingSchedule,
  type MeetingScheduleInput,
} from './meeting.js';
export {
  audienceKey,
  categoryKey,
  categoryShortKey,
  chargeDetailKey,
  chargeKey,
  consumptionBasisKey,
  deedDeniedKey,
  emergencyHintKey,
  inspectionKindKey,
  meterKindKey,
  meterUnitKey,
  noticeKindKey,
  plainBasisKey,
  pollRuleKey,
  responsibleKey,
  scopeKey,
  statusKey,
  targetKey,
  ticketStatusKey,
  voteChoiceKey,
  zoneKey,
  zoneNextKey,
  type ZoneName,
} from './keys.js';
export { houseMood, type HouseMood } from './mood.js';
export { isWearDue, wearOf, type Wear } from './wear.js';
export {
  ELDER_TERM_YEARS,
  INITIATIVE_SHARE,
  POLL_RULES,
  areaToQuorum,
  areasMissingNote,
  castVote,
  checkShare,
  countVotes,
  electElder,
  elderNow,
  isOpen,
  needsClosing,
  sign,
  standingOf,
  type CastVoteInput,
  type ElderCandidate,
  type Eldership,
  type Initiative,
  type InitiativeStanding,
  type Poll,
  type PollKind,
  type PollMode,
  type PollResult,
  type PollRule,
  type Signature,
  type SignInput,
  type Vote,
  type VoteChoice,
} from './voting.js';
export {
  METER_RULES,
  NEIGHBOURS_FOR_COMPARISON,
  NEIGHBOUR_FACTOR,
  READING_WINDOW,
  SPIKE_FACTOR,
  VERIFICATION_WARNING_DAYS,
  acceptReading,
  compareToNeighbours,
  consumption,
  daysLeftInWindow,
  isReadingWindow,
  isSameMonth,
  isSpike,
  periodOf,
  verificationState,
  type Meter,
  type MeterKind,
  type MeteringDevice,
  type MeterRule,
  type ReadingWindow,
  type ConsumptionComparison,
  type Reading,
  type SubmitReadingInput,
  type VerificationState,
} from './meters.js';
export { formatClock, formatDate, formatDay, formatMoment, formatSpan, formatWeekday } from './moment.js';
export {
  CATEGORY_RULES,
  NORM_BLOCKAGE_HOURS,
  NORM_EMERGENCY_HOURS,
  NORM_LOCALIZATION_MINUTES,
  PRIORITY_FACTOR,
  assessDeadlineRisk,
  assigneeLoad,
  collectCategoryStats,
  compareByUrgency,
  computeDeadlines,
  deadlineCrossedIn,
  emergencyHint,
  isOverdue,
  isReactionOverdue,
  isResolutionOverdue,
  missedDeadline,
  missedReaction,
  missedResolution,
  reactedAt,
  settledAt,
  timeToDeadline,
  timeToResolution,
  warningCrossedIn,
  WARNING_SHARE,
  type CategoryRule,
  type CategoryStats,
  type DeadlineRisk,
  type Deadlines,
  type NormLimit,
  type RiskAssessment,
} from './sla.js';
export {
  ACCEPTANCE_REMINDER_SHARE,
  AUTO_CONFIRM_AFTER_HOURS,
  MESSAGE_MAX_LENGTH,
  MATERIAL_TITLE_LENGTH,
  checkMaterials,
  CLOSED_STATUSES,
  STAFF_STATUS_TITLES,
  STATUS_TITLES,
  statusTitle,
  OPEN_STATUSES,
  RATING_RANGE,
  TRANSITIONS,
  acceptanceReminderCrossedIn,
  addMessage,
  allowedTransitions,
  applyTransition,
  findTransition,
  isAutoConfirmDue,
  isFinal,
  reportedDoneAt,
  statusChanges,
  type AddMessageInput,
  type ApplyTransitionInput,
  type Transition,
} from './status.js';
export {
  BASIS_TITLES,
  DEFAULT_TARIFFS,
  PAYMENT_DUE_DAY,
  chargesFor,
  leftToPay,
  type ChargeInput,
  type ChargeLine,
  type Charges,
  type Tariffs,
} from './billing.js';
export {
  OUTAGE_LIMITS,
  OUTAGE_REDUCTION_PER_HOUR,
  excessOutageHours,
  outageReduction,
  type Outage,
  type OutageLimit,
} from './outages.js';
export {
  AVERAGE_MONTHS,
  AVERAGE_WINDOW,
  NORM_FACTOR,
  NORM_FACTOR_KINDS,
  NORM_PER_AREA,
  NORM_PER_PERSON,
  estimateConsumption,
  normFor,
  type ConsumptionBasis,
  type Estimate,
  type EstimateInput,
  type NormInput,
} from './norms.js';
export {
  commonNeedsFor,
  commonNeedsTitle,
  type CommonNeedsInput,
  type HouseMeter,
} from './common.js';
export {
  PENALTY_FREE_DAYS,
  PENALTY_SOFT_UNTIL_DAY,
  overdueDays,
  penaltyFor,
} from './penalty.js';
export { WORKING_HOURS, dayIn, hourIn, isWorkingHours, onCall, type OnDutyLike } from './duty.js';
export {
  describeUntil,
  describeWork,
  explainingWork,
  isUnderway,
  worksCrossedIn,
  WORKS_WARNING_HOURS,
  type PlannedWork,
  type WorksEvent,
} from './works.js';
export {
  INSPECTION_RULES,
  checkItem,
  checkedCount,
  isFinished,
  isInspectionOverdue,
  planInspection,
  type CheckItemInput,
  type EquipmentKind,
  type Inspection,
  type InspectionItem,
  type InspectionKind,
  type InspectionRule,
  type ItemState,
  type NewInspectionInput,
} from './inspection.js';
export {
  DEFAULT_TIME_ZONE,
  COMPANY_ROLES,
  DomainError,
  NOTICE_KINDS,
  NOTICE_TITLES,
  ROLES,
  isCompanyStaff,
  type NoticeKind,
  FINAL_STATUSES,
  type AnnouncementAudience,
  type Apartment,
  type ErrorCode,
  type Attachment,
  type Material,
  type OriginalText,
  type Priority,
  type RequestCategory,
  type RequestEvent,
  type RequestJoin,
  type RequestStatus,
  type RequestTarget,
  type Role,
  type ServiceRequest,
} from './types.js';

export { days, formatArea, formatMeterValue, formatMoney, months, plural } from './russian.js';
export { crossedIn, inPeriod, median, roundMoney } from './numbers.js';
export { mentionsNumber, numberFromWords } from './numerals.js';
export {
  addWorkingDays,
  answerDueAt,
  closeTicket,
  compareTickets,
  isAcknowledgement,
  isAnswerOverdue,
  openTicket,
  PUBLIC_HOLIDAYS,
  replyToTicket,
  SUPPORT_ANSWER_DAYS,
  TICKET_STATUS_TITLES,
  ticketStatusTitle,
  waitingSince,
  waitsForAnswer,
  type OpenTicketInput,
  type SupportTicket,
  type TicketMessage,
  type TicketReply,
  type TicketStatus,
} from './helpdesk.js';
export {
  DEFAULT_STICKER_STYLE,
  STICKER_NOTE_MAX_LENGTH,
  STICKER_STYLES,
  cleanStickerNote,
  isStickerStyle,
  planStickers,
  stickerFileName,
  type StickerApartment,
  type StickerLook,
  type StickerPlan,
  type StickerPlanOptions,
  type StickerStyle,
  type StickerStyleName,
} from './stickers.js';
export {
  RECEPTION_HORIZON_DAYS,
  TOPIC_MAX_LENGTH,
  VISIT_MINUTES,
  VISIT_MINUTES_RANGE,
  WEEKDAY_TITLES,
  bookVisit,
  cancelVisit,
  checkReception,
  checkVisitMinutes,
  completeVisit,
  formatReception,
  isActiveVisit,
  minutesOfDay,
  momentIn,
  partsIn,
  receptionSlots,
  writeVisit,
  type ReceptionWindow,
  type Visit,
  type VisitStatus,
  type WriteVisitInput,
} from './reception.js';
export {
  HANDOFF_BASIS,
  HANDOFF_HOURS,
  HANDOFF_STATUS_TITLES,
  HANDOFF_TITLES,
  RESPONSIBLE_TITLES,
  handoffDueAt,
  isHandoffOverdue,
  isHandoffTarget,
  responsibilityFor,
  type Handoff,
  type HandoffStatus,
  type HandoffTarget,
  type Responsibility,
  type ResponsibleKind,
  type Spreading,
} from './responsibility.js';
